<?php
/**
 * @file
 * Test module for verifying backup capabilities.
 */

/**
 * Implements hook_menu().
 */
function backup_test_menu() {
  $items = array();

  $items['backup-test/settings'] = array(
    'title' => 'Backup test form',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('backup_test_settings_form'),
    // There is no separate permission for creating backups.
    'access arguments' => array('restore site backups'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Form that contains Backup form capabilities.
 */
function backup_test_settings_form(array $form, array &$form_state) {
  include_once BACKDROP_ROOT . '/core/includes/backup.inc';

  $form['backup_limit'] = array(
    '#type' => 'number',
    '#title' => t('Backup limit'),
    '#default_value' => config_get('system.core', 'backup_limit'),
    '#min' => 1,
    '#max' => 100,
  );

  // Add in the Backup settings form, with settings.
  $form = backup_settings_form($form, $form_state, array(
    'show_settings' => TRUE,
    'show_default_targets' => TRUE,
  ));

  // Add our additional submit handler and the one provided by backup.inc.
  $form['#submit'] = array(
    'backup_test_settings_form_submit',
    'backup_settings_form_submit',
  );

  return $form;
}

/**
 * Submit handler for _backup_test_settings_form().
 */
function backup_test_settings_form_submit(array $form, array &$form_state) {
  config_set('system.core', 'backup_limit', $form_state['values']['backup_limit']);
}
