deploy:
  branch:
    server: backdrop.vps-private.net
    username: qa
    dir: '{home}/github/branch/{branch}'
    env_vars:
      domain: '{branch}.qa.backdrop.vps-private.net'
      site_name: '{branch} testing site'
      site_mail: 'testing@{branch}.qa.backdrop.vps-private.net'
      account_name: admin
      account_mail: 'testing@{branch}.qa.backdrop.vps-private.net' 
    scripts:
      init: '{deploy_dir}/core/scripts/init_deploy.sh'
    webhooks:
      init: http://github.backdrop.expert/webhook/init
      remove: http://github.backdrop.expert/webhook/remove
  pull_request:
    server: backdrop.vps-private.net
    username: qa
    dir: '{home}/github/pr/{pr_number}'
    env_vars:
      domain: '{pr_number}.qa.backdrop.vps-private.net'
      site_name: '{pr_number} testing site'
      site_mail: 'testing@{pr_number}.qa.backdrop.vps-private.net'
      account_name: admin
      account_mail: 'testing@{pr_number}.qa.backdrop.vps-private.net' 
    scripts:
      init: '{deploy_dir}/core/scripts/init_deploy.sh'
      remove: '{deploy_dir}/core/scripts/remove.sh'
    webhooks:
      init: http://github.backdrop.expert/webhook/init
      remove: http://github.backdrop.expert/webhook/remove
