<?php

/**
 * @file
 * Install, update and uninstall functions for the Date Views module.
 */


/**
 * Move date_views settings from variables to config.
 */
function date_views_update_1000() {
  // Migrate variables to config.
  $config = config('date_views.settings');
  $config->set('date_views_month_format_with_year', update_variable_get('date_views_month_format_with_year', 'F Y'));
  $config->set('date_views_month_format_without_year', update_variable_get('date_views_month_format_without_year', 'F'));
  $config->set('date_views_day_format_with_year', update_variable_get('date_views_day_format_with_year', 'l, F j, Y'));
  $config->set('date_views_day_format_without_year', update_variable_get('date_views_day_format_without_year', 'l, F j'));
  $config->set('date_views_week_format_with_year', update_variable_get('date_views_week_format_with_year', 'F j, Y'));
  $config->set('date_views_week_format_without_year', update_variable_get('date_views_week_format_without_year', 'F j'));
  $config->save();

  // Delete variables.
  update_variable_del('date_views_month_format_with_year');
  update_variable_del('date_views_month_format_without_year');
  update_variable_del('date_views_day_format_with_year');
  update_variable_del('date_views_day_format_without_year');
  update_variable_del('date_views_week_format_with_year');
  update_variable_del('date_views_week_format_without_year');
}

/**
 * Implements hook_update_last_removed().
 */
function date_views_update_last_removed() {
  return 7200;
}
