<?php
// $Id$

/**
 * Implements hook_permission().
 */
function views_test_permission() {
  return array(
    'views_test test permission' => array(
      'title' => t('Test permission'),
      'description' => t('views_test test permission'),
    ),
  );
}

/**
 * Implements hook_views_api().
 */
function views_test_views_api() {
  return array(
    'api' => '3.0-alpha1',
    'template path' => drupal_get_path('module', 'views_test') . '/templates',
  );
}

/**
 * Implements hook_views_data()
 */
function views_test_views_data() {
  return variable_get('views_test_views_data', array());
}

/**
 * Implements hook_views_plugins()
 */
function views_test_views_plugins() {
  return variable_get('views_test_views_plugins', array());
}
