<?php

/**
 * @file
 * Helper module for the path tests.
 */

/**
 * Resets the path test results.
 */
function path_test_reset() {
  state_set('path_test_results', array());
}

/**
 * Implements hook_path_update().
 */
function path_test_path_update($path) {
  $results = state_get('path_test_results', array());
  $results['hook_path_update'] = $path;
  state_set('path_test_results', $results);
}
