<?php
/**
 * @file
 * Tests that requirements data can be altered/deleted.
 */

/**
 * Implements hook_requirements_alter().
 */
function requirements_test_alterable_requirements_alter(array &$requirements) {
  // Change the title of the 'requirements_test_alterable' entry.
  $requirements['requirements_test_alterable']['title'] = t('Requirements 1 Test - Changed');
  // Decrease the severity of the 'requirements_test_alterable' entry.
  $requirements['requirements_test_alterable']['severity'] = REQUIREMENT_WARNING;
  // Delete the 'requirements_test_deletable' entry altogether.
  unset($requirements['requirements_test_deletable']);
}
