<?php
/**
 * @file
 * Provides integration with the CKEditor WYSIWYG editor.
 */

define('CKEDITOR5_VERSION', '38.0.1');

/**
 * Implements hook_menu().
 */
function ckeditor5_menu() {
  $items['ckeditor5/upload/image/%filter_format'] = array(
    'title' => 'Upload image',
    'page callback' => 'ckeditor5_image_upload',
    'page arguments' => array(3),
    'access callback' => 'filter_dialog_access',
    'access arguments' => array(3, 'image'),
    'theme callback' => 'ajax_base_page_theme',
    'delivery callback' => 'backdrop_json_deliver',
    'type' => MENU_CALLBACK,
    'file' => 'ckeditor5.pages.inc',
  );
  return $items;
}

/**
 * Implements hook_editor_info().
 */
function ckeditor5_editor_info() {
  $editors['ckeditor5'] = array(
    'label' => t('CKEditor 5'),
    'library' => array('ckeditor5', 'backdrop.ckeditor5'),
    'default settings' => array(
      'toolbar' => array(
        'bold', 'italic', 'blockQuote', 'heading', '|',
        'bulletedList', 'numberedList', '|',
        'alignment:left', 'alignment:center', 'alignment:right', '|',
        'link', 'backdropImage', '|',
        'sourceEditing', 'removeFormat'
      ),
      'heading_list' => array('p', 'h3', 'h4', 'h5'),
      'style_list' => array(),
    ),
    'file' => 'ckeditor5.admin.inc',
    'settings callback' => 'ckeditor5_settings_form',
    'js settings callback' => 'ckeditor5_get_config',
  );

  return $editors;
}

/**
 * Implements hook_library_info().
 */
function ckeditor5_library_info() {
  $module_path = backdrop_get_path('module', 'ckeditor5');

  $libraries['backdrop.ckeditor5.admin'] = array(
    'title' => 'Administrative library for configuring CKEditor.',
    'version' => BACKDROP_VERSION,
    'js' => array(
      $module_path . '/js/ckeditor5.admin.js' => array(),
    ),
    'css' => array(
      $module_path . '/css/ckeditor5.admin.css' => array(),
    ),
    'dependencies' => array(
      array('system', 'ui.sortable'),
      array('system', 'ui.draggable'),
    ),
  );
  $libraries['backdrop.ckeditor5'] = array(
    'title' => 'Backdrop behavior to enable CKEditor on textareas.',
    'version' => BACKDROP_VERSION,
    'js' => array(
      $module_path . '/js/ckeditor5.js' => array(),
    ),
    'css' => array(
      $module_path . '/css/ckeditor5.css' => array(),
    ),
    'dependencies' => array(
      array('filter', 'filter'),
      array('system', 'backdrop.ajax'),
      array('ckeditor5', 'ckeditor5'),
      // CKEditor 5 does not provide its own plugin loader, so any added
      // potentially needed plugins are added as dependencies.
      // @todo: Improve loading to use libraries only when needed.
      array('ckeditor5', 'backdrop.ckeditor5.backdrop-basic-styles'),
      array('ckeditor5', 'backdrop.ckeditor5.backdrop-image'),
      array('ckeditor5', 'backdrop.ckeditor5.backdrop-link'),
    ),
  );

  $libraries['backdrop.ckeditor5.backdrop-basic-styles'] = array(
    'title' => 'CKEditor plugin to convert basic HTML tags to preferred tags.',
    'version' => BACKDROP_VERSION,
    'js' => array(
      $module_path . '/js/plugins/backdrop-basic-styles/backdrop-basic-styles.js' => array(),
    ),
  );
  $libraries['backdrop.ckeditor5.backdrop-image'] = array(
    'title' => 'Integrates uploading images with CKEditor 5.',
    'version' => BACKDROP_VERSION,
    'js' => array(
      $module_path . '/js/plugins/backdrop-image/backdrop-image.js' => array(),
    ),
  );
  $libraries['backdrop.ckeditor5.backdrop-link'] = array(
    'title' => 'Provides a CKEditor 5 plugin for linking with a dialog.',
    'version' => BACKDROP_VERSION,
    'js' => array(
      $module_path . '/js/plugins/backdrop-link/backdrop-link.js' => array(),
    ),
  );

  $libraries['ckeditor5'] = array(
    'title' => 'Loads the main CKEditor library.',
    'version' => CKEDITOR5_VERSION,
    'js' => array(
      // CKEditor is a large library but already compressed. Do not aggregate.
      $module_path . '/lib/ckeditor5/build/ckeditor.js' => array('preprocess' => FALSE, 'group' => JS_LIBRARY),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_theme().
 */
function ckeditor5_theme() {
  return array(
    'ckeditor5_settings_toolbar' => array(
      'variables' => array('format' => NULL, 'plugins' => NULL),
      'file' => 'ckeditor5.theme.inc',
    ),
  );
}

/**
 * Implements hook_js_alter().
 *
 * Adds a matching CKEditor 5 translation file if the UI is non-English.
 */
function ckeditor5_js_alter(&$javascript) {
  global $language;
  if ($language->langcode === 'en') {
    return;
  }

  $module_path = backdrop_get_path('module', 'ckeditor5');
  $build_path = $module_path . '/lib/ckeditor5/build';
  $js_path = $build_path . '/ckeditor.js';
  $translation_path = $build_path . '/translations/' . $language->langcode . '.js';

  // If the ckeditor.js library is present AND a translation file exists for
  // the current language, append the translation file to the JavaScript array.
  if (isset($javascript[$js_path]) && file_exists($translation_path)) {
    // Copy the CKEditor library settings, which will be nearly identical the
    // translation settings (same preprocessing, scope, weight, version, etc.)
    $javascript[$translation_path] = $javascript[$js_path];
    $javascript[$translation_path]['data'] = $translation_path;
  }
}

/**
 * Retrieves the full list of installed CKEditor plugins.
 */
function ckeditor5_plugins() {
  $plugins = module_invoke_all('ckeditor5_plugins');
  backdrop_alter('ckeditor5_plugins', $plugins);
  return $plugins;
}

/**
 * Implements hook_ckeditor5_plugins().
 *
 * Return a list of all plugins provided by this module.
 */
function ckeditor5_ckeditor5_plugins() {
  $image_prefix = backdrop_get_path('module', 'ckeditor5') . '/icons';

  // The "essentials" plugin is necessary for any kind of basic editing. Basic
  // formatting buttons are included under this plugin, even though they are
  // not technically provided by it.
  $plugins['essentials.Essentials'] = array(
    'buttons' => array(
      // Provided by the basic-styles plugin.
      // See https://ckeditor.com/docs/ckeditor5/latest/features/basic-styles.html
      'bold' => array(
        'label' => t('Bold'),
        'image' => $image_prefix . '/bold.svg',
        'required_html' => array('<strong>'),
        'plugin_dependencies' => array('basicStyles.Bold'),
      ),
      'italic' => array(
        'label' => t('Italic'),
        'image' => $image_prefix . '/italic.svg',
        // CKEditor defaults to <i>, the BackdropBasicStyles plugin converts it
        // to <em> for backwards-compatibility with Backdrop standards.
        'required_html' => array('<em>'),
        'plugin_dependencies' => array('basicStyles.Italic', 'backdropBasicStyles.BackdropBasicStyles'),
      ),
      'underline' => array(
        'label' => t('Underline'),
        'image' => $image_prefix . '/underline.svg',
        // Unlike CKEditor 4, we conform to CKEditor 5's preference for the <u>
        // tag for underlined content. The BackdropBasicStyles plugin converts
        // legacy <span class="underline"> content to use <u>.
        'required_html' => array('<u>'),
        'plugin_dependencies' => array('basicStyles.Underline', 'backdropBasicStyles.BackdropBasicStyles'),
      ),
      'strikethrough' => array(
        'label' => t('Strike-through'),
        'image' => $image_prefix . '/strikethrough.svg',
        // CKEditor defaults to <s>, the BackdropBasicStyles plugin converts it
        // to <del> for backwards-compatibility with Backdrop standards.
        'required_html' => array('<del>'),
        'plugin_dependencies' => array('basicStyles.Strikethrough', 'backdropBasicStyles.BackdropBasicStyles'),
      ),
      'code' => array(
        'label' => t('Code'),
        'image' => $image_prefix . '/code.svg',
        'required_html' => array('<code>'),
        'plugin_dependencies' => array('basicStyles.Code'),
      ),
      'subscript' => array(
        'label' => t('Subscript'),
        'image' => $image_prefix . '/subscript.svg',
        'required_html' => array('<sub>'),
        'plugin_dependencies' => array('basicStyles.Subscript'),
      ),
      'superscript' => array(
        'label' => t('Superscript'),
        'image' => $image_prefix . '/superscript.svg',
        'required_html' => array('<sup>'),
        'plugin_dependencies' => array('basicStyles.Superscript'),
      ),
      // Separator, part of toolbar core.
      // See https://ckeditor.com/docs/ckeditor5/latest/features/toolbar/toolbar.html#separating-toolbar-items
      '|' => array(
        'label' => t('Separator'),
        'image_alternative' => '<span class="ckeditor5-separator" title="' . t('Button separator') . '" aria-label="' . t('Button separator') . '">&nbsp;</span>',
        'attributes' => array('class' => array('ckeditor5-button-separator')),
        'multiple' => TRUE,
      ),
      // Line break, part of toolbar core.
      // See https://ckeditor.com/docs/ckeditor5/latest/features/toolbar/toolbar.html#multiline-wrapping-toolbar
      '-' => array(
        'label' => t('Line Break'),
        'image_alternative' => '<span class="ckeditor5-line-break" title="' . t('Line break') . '" aria-label="' . t('Line break') . '">&nbsp;</span>',
        'multiple' => TRUE,
      ),
    ),
    'enabled callback' => TRUE,
  );

  // See https://ckeditor.com/docs/ckeditor5/latest/features/text-alignment.html
  $plugins['alignment.Alignment'] = array(
    'buttons' => array(
      'alignment' => array(
        'label' => t('Alignment'),
        'image_alternative' => '<span class="ckeditor5-button-dropdown">' . t('Alignment') . '<span class="ckeditor5-button-arrow"></span></span>',
        'required_html' => array('<p class="text-align-left text-align-center text-align-right text-align-justify">'),
      ),
      'alignment:left' => array(
        'label' => t('Align left'),
        'image' => $image_prefix . '/align-left.svg',
        'required_html' => array('<p class="text-align-left">'),
      ),
      'alignment:center' => array(
        'label' => t('Align center'),
        'required_html' => array('<p class="text-align-center">'),
        'image' => $image_prefix . '/align-center.svg',
      ),
      'alignment:right' => array(
        'label' => t('Align right'),
        'required_html' => array('<p class="text-align-right">'),
        'image' => $image_prefix . '/align-right.svg',
      ),
      'alignment:justify' => array(
        'label' => t('Justify'),
        'required_html' => array('<p class="text-align-justify">'),
        'image' => $image_prefix . '/align-justify.svg',
      ),
    ),
    'plugin_dependencies' => array('alignment.Alignment'),
    'config' => array(
      'alignment' => array(
        'options' => array(
          array('name' => 'left', 'className' => 'text-align-left'),
          array('name' => 'center', 'className' => 'text-align-center'),
          array('name' => 'right', 'className' => 'text-align-right'),
          array('name' => 'justify', 'className' => 'text-align-justify'),
        ),
      ),
    ),
  );

  // See https://ckeditor.com/docs/ckeditor5/latest/features/indent.html
  $plugins['indent.Indent'] = array(
    'buttons' => array(
      'indent' => array(
        'label' => t('Indent'),
        'image' => $image_prefix . '/indent.svg',
        'required_html' => array('<p class="indent1 indent2 indent3">'),
      ),
      'outdent' => array(
        'label' => t('Outdent'),
        'image' => $image_prefix . '/outdent.svg',
        'required_html' => array('<p class="indent1 indent2 indent3">'),
      ),
    ),
    'plugin_dependencies' => array('indent.IndentBlock'),
    'config' => array(
      'indentBlock' => array(
        'classes' => array('indent1', 'indent2', 'indent3'),
      ),
    ),
  );

  // See https://ckeditor.com/docs/ckeditor5/latest/features/lists/document-lists.html
  $plugins['list.DocumentList'] = array(
    'buttons' => array(
      'bulletedList' => array(
        'label' => t('Bullet list'),
        'image' => $image_prefix . '/bulleted-list.svg',
        'image_rtl' => $image_prefix . '/bulleted-list-rtl.svg',
        'required_html' => array('<ul>', '<li>'),
      ),
      'numberedList' => array(
        'label' => t('Numbered list'),
        'image' => $image_prefix . '/numbered-list.svg',
        'image_rtl' => $image_prefix . '/numbered-list-rtl.svg',
        'required_html' => array('<ol>', '<li>'),
      ),
    ),
    'plugin_dependencies' => array('list.DocumentListProperties'),
    'config' => array(
      'list' => array(
        'properties' => array(
          'reversed' => TRUE,
          'startIndex' => TRUE,
          'styles' => array('useAttribute' => TRUE),
        ),
      ),
    ),
  );

  // See https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html
  $plugins['codeBlock.CodeBlock'] = array(
    'buttons' => array(
      'codeBlock' => array(
        'label' => t('Code'),
        'image' => $image_prefix . '/code.svg',
        'required_html' => array('<code>', '<pre>'),
      ),
    ),
  );

  // See https://ckeditor.com/docs/ckeditor5/latest/features/block-quote.html
  $plugins['blockQuote.BlockQuote'] = array(
    'buttons' => array(
      'blockQuote' => array(
        'label' => t('Block quote'),
        'image' => $image_prefix . '/block-quote.svg',
        'required_html' => array('<blockquote>'),
      ),
    ),
  );

  // See https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html
  $plugins['sourceEditing.SourceEditing'] = array(
    'buttons' => array(
      'sourceEditing' => array(
        'label' => t('Source'),
        'image' => $image_prefix . '/source-editing.svg',
      ),
    ),
  );

  // See https://ckeditor.com/docs/ckeditor5/latest/features/horizontal-line.html
  $plugins['horizontalLine.HorizontalLine'] = array(
    'buttons' => array(
      'horizontalLine' => array(
        'label' => t('Horizontal line'),
        'image' => $image_prefix . '/horizontal-line.svg',
        'required_html' => array('<hr>'),
      ),
    ),
  );

  // See https://ckeditor.com/docs/ckeditor5/latest/features/remove-format.html
  $plugins['removeFormat.RemoveFormat'] = array(
    'buttons' => array(
      'removeFormat' => array(
        'label' => t('Remove format'),
        'image' => $image_prefix . '/remove-format.svg',
      ),
    ),
  );

  // See https://ckeditor.com/docs/ckeditor5/latest/features/autoformat.html
  $plugins['autoformat.Autoformat'] = array(
    // @todo: Provide a configuration option to toggle.
    'enabled callback' => TRUE,
  );

  // See https://ckeditor.com/docs/ckeditor5/latest/features/tables/tables.html
  $plugins['table.Table'] = array(
    'buttons' => array(
      'insertTable' => array(
        'label' => t('Table'),
        'image' => $image_prefix . '/table.svg',
        'required_html' => array(
          '<table>',
          '<td rowspan colspan>',
          '<th rowspan colspan>',
          '<tr>',
          '<thead>',
          '<tbody>',
          '<tfoot>',
          '<caption>',
        ),
      ),
    ),
    'plugin_dependencies' => array('table.TableToolbar', 'table.TableCaption', 'table.PlainTableOutput', 'table.TableCellProperties', 'table.TableColumnResize', 'table.TableProperties'),
    'config' => array(
      'table' => array(
        'contentToolbar' => array(
          'tableColumn',
          'tableRow',
          'mergeTableCells',
          'toggleTableCaption',
        ),
      ),
    ),
  );

  // See https://ckeditor.com/docs/ckeditor5/latest/features/headings.html
  $plugins['heading.Heading'] = array(
    'buttons' => array(
      'heading' => array(
        'label' => t('Headings'),
        'image_alternative' => '<span class="ckeditor5-button-dropdown">' . t('Headings') . '<span class="ckeditor5-button-arrow"></span></span>',
      ),
    ),
  );

  // See https://ckeditor.com/docs/ckeditor5/latest/features/style.html
  $plugins['style.Style'] = array(
    'buttons' => array(
      'style' => array(
        'label' => t('Font style'),
        'image_alternative' => '<span class="ckeditor5-button-dropdown">' . t('Styles') . '<span class="ckeditor5-button-arrow"></span></span>',
        'plugin_dependencies' => array('htmlSupport.GeneralHtmlSupport'),
      ),
    ),
  );

  // See https://ckeditor.com/docs/ckeditor5/latest/features/special-characters.html
  $plugins['specialCharacters.SpecialCharacters'] = array(
    'buttons' => array(
      'specialCharacters' => array(
        'label' => t('Special characters'),
        'image' => $image_prefix . '/special-characters.svg',
        'plugin_dependencies' => array('specialCharacters.SpecialCharactersEssentials'),
      ),
    ),
  );

  // See https://ckeditor.com/docs/ckeditor5/latest/features/undo-redo.html
  $plugins['undo.Undo'] = array(
    'buttons' => array(
      'undo' => array(
        'label' => t('Undo'),
        'image' => $image_prefix . '/undo.svg',
        'image_rtl' => $image_prefix . '/undo-rtl.svg',
      ),
      'redo' => array(
        'label' => t('Redo'),
        'image' => $image_prefix . '/redo.svg',
        'image_rtl' => $image_prefix . '/redo-rtl.svg',
      ),
    ),
  );

  // Plugin that converts CKEditor preferred tags to Backdrop preferred tags,
  // such as converting <s> to <del> or <i> to <em>.
  $plugins['backdropBasicStyles.BackdropBasicStyles'] = array(
    'library' => array('ckeditor5', 'backdrop.ckeditor5.backdrop-basic-styles'),
    'enabled callback' => TRUE,
  );

  // The BackdropImage plugin extends the default CKEditor Image plugin.
  $plugins['backdropImage.BackdropImage'] = array(
    'library' => array('ckeditor5', 'backdrop.ckeditor5.backdrop-image'),
    'buttons' => array(
      'backdropImage' => array(
        'label' => t('Image'),
        'plugin_dependencies' => array(
          'image.Image',
          'image.ImageToolbar',
          'image.ImageInsertUI',
          'image.ImageUpload',
        ),
        'required_html' => array(
          '<img src alt height width data-file-id>',
        ),
        'image' => $image_prefix . '/image.svg',
      ),
    ),
    'config' => array(
      'image' => array(
        'toolbar' => array(
          'toggleImageCaption',
          'imageTextAlternative',
        ),
        'upload' => array(
          'type' => image_get_supported_extensions(),
        ),
      ),
    ),
  );

  // The BackdropImageCaption plugin provides consistent behaviors for image
  // captions.
  // @todo: This plugin is now merged with the main backdrop-image plugin.
  // Move the required_html to be added in ckeditor5_get_config()
  // or elsewhere.
  $plugins['backdropImageCaption.BackdropImageCaption'] = array(
    'enabled callback' => 'ckeditor5_image_plugin_check',
    'required_html' => array(
      '<img data-caption>',
      '<figure>',
      '<figcaption data-placeholder>',
    ),
  );

  // The BackdropLink plugin extends the build in link button.
  $plugins['link.Link'] = array(
    'buttons' => array(
      'link' => array(
        'label' => t('Link'),
        'image' => $image_prefix . '/link.svg',
        'required_html' => array('<a href target class id title rel data-file-id>'),
        'plugin_dependencies' => array('backdropLink.BackdropLink'),
      ),
    ),
    // Append the "Link" button to the image balloon toolbar.
    'config' => array(
      'image' => array(
        'toolbar' => array('|', 'linkImage'),
      ),
      'backdropLink' => array(
        // Specify an array of CKEditor model name => attribute name values.
        // These attributes are then allowed to be changed via the Backdrop
        // link dialog. Additional attributes can be added here to prevent
        // CKEditor from striping out attributes on anchor tags.
        'extraAttributes' => array(
          'linkTarget' => 'target',
          'linkClass' => 'class',
          'linkTitle' => 'title',
          'linkId' => 'id',
          'linkRel' => 'rel',
          'linkDataFileId' => 'data-file-id',
        ),
      ),
    ),
  );

  $plugins['backdropLink.BackdropLink'] = array(
    'library' => array('ckeditor5', 'backdrop.ckeditor5.backdrop-link'),
  );

  return $plugins;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Manipulate the image insert form to describe CKEditor-integration.
 */
function ckeditor5_form_filter_format_editor_image_form_alter(&$form, $form_state) {
  $format = $form_state['format'];
  if ($format->editor === 'ckeditor5') {
    $form['caption']['#description'] = t('If checked, a caption area will appear in the editor.');
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Manipulate the link dialog form to remove setting the link text, which is
 * not (yet) supported).
 */
function ckeditor5_form_filter_format_editor_link_form_alter(&$form, $form_state) {
  $format = $form_state['format'];
  if ($format->editor === 'ckeditor5') {
    $form['text']['#access'] = FALSE;
  }
}

/**
 * Enabled callback for hook_ckeditor5_plugins().
 *
 * Checks if our Caption plugin should be enabled based on the configuration of
 * a text format and editor.
 *
 * @param $format
 *   The filter format object for which CKEditor is checking settings.
 * @param $plugin_name
 *   The plugin that is being checked.
 *
 * @return bool
 *   TRUE if the image plugin is enabled, FALSE otherwise.
 */
function ckeditor5_image_plugin_check($format, $plugin_name) {
  // Automatically enable caption support if the BackdropImage button is enabled.
  foreach ($format->editor_settings['toolbar'] as $row) {
    foreach ($row as $button_group) {
      if (in_array('BackdropImage', $button_group['items'])) {
        return TRUE;
      }
    }
  }
  return FALSE;
}

/**
 * Editor JS settings callback; Add CKEditor config to the page for a format.
 *
 * Note that this function uses the term "config" to match that of CKEditor's
 * own terminology. It is not related to Backdrop's configuration system.
 *
 * See https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/configuration.html
 *
 * @param $format
 *   The filter format object for which CKEditor is adding its config.
 * @param $existing_settings
 *   Settings that have already been added to the page by filters.
 */
function ckeditor5_get_config($format, $existing_settings) {
  global $language;

  // Loop through all available plugins and check to see if it has been
  // explicitly enabled. At the same time, associate each plugin with its
  // buttons (if any) so we can check if the plugin should be enabled implicitly
  // based on the toolbar.
  $plugin_info = ckeditor5_plugins();
  $external_css = array();
  $all_buttons = array();
  $plugins = array();
  $libraries = array();
  foreach ($plugin_info as $plugin_name => $plugin) {
    // Check if this plugin should be enabled.
    if (isset($plugin['enabled callback'])) {
      if ($plugin['enabled callback'] === TRUE || $plugin['enabled callback']($format, $plugin_name)) {
        $libraries[] = $plugin['library'];
        $plugins[] = $plugin_name;
        if ($plugin['plugin_dependencies']) {
          // Add the plugin and its dependencies to the list of plugins.
          $plugins = array_merge($plugins, $plugin['plugin_dependencies']);
        }
      }
    }
    // Associate each button with its providing plugin.
    if (isset($plugin['buttons'])) {
      foreach ($plugin['buttons'] as $button_name => &$button) {
        $button['plugin'] = $plugin;
        $button['plugin']['name'] = $plugin_name;
        unset($button['plugin']['buttons']);
      }
      $all_buttons = array_merge($all_buttons, $plugin['buttons']);
    }
  }

  // Record needed plugins based on use in the toolbar.
  $toolbar = array();
  foreach ($format->editor_settings['toolbar'] as $button_name) {
    // Sanity check that the button exists in our installation.
    if (isset($all_buttons[$button_name])) {
      // Add in plugin dependencies for this particular button.
      if (isset($all_buttons[$button_name]['plugin']['name'])) {
        $plugins[] = $all_buttons[$button_name]['plugin']['name'];
      }
      if (isset($all_buttons[$button_name]['plugin_dependencies'])) {
        $plugins = array_merge($plugins, $all_buttons[$button_name]['plugin_dependencies']);
      }
    }
    $toolbar[] = $button_name;
  }
  // Collect a list of CSS files to be added to the editor instance.
  $css = array(
    backdrop_get_path('module', 'system') . '/css/system.css',
    backdrop_get_path('module', 'ckeditor5') . '/css/ckeditor5-iframe.css',
  );
  $css = array_merge($css, $external_css, _ckeditor5_theme_css());
  backdrop_alter('ckeditor5_css', $css, $format);

  // Convert all paths to be relative to root.
  foreach ($css as $key => $css_path) {
    $css[$key] = base_path() . $css_path;
  }

  // Remove duplicates and ensure it is numerically ordered so it is an array
  // when passed to the front-end JavaScript.
  $plugin_list = array_values(array_unique($plugins));

  // Initialize reasonable defaults that provide expected basic behavior.
  $config = array(
    'language' => $language->langcode,
    'toolbar' => array(
      'items' => $toolbar,
      'shouldNotGroupWhenFull' => TRUE,
    ),
    // Plugin list is not a "real" CKEditor configuration value. It is converted
    // from an array of strings to variables references in the ckeditor.js file.
    'pluginList' => $plugin_list,

    //'contentsCss' => array_values($css),
  );

  // Add default settings from plugins.
  foreach ($plugin_list as $plugin_name) {
    if (isset($plugin_info[$plugin_name]['config'])) {
      $config = array_merge($config, $plugin_info[$plugin_name]['config']);
    }
  }

  // Add the allowedContent setting, which ensures CKEditor only allows tags
  // and attributes that are allowed by the text format for this text editor.
  //list($config['allowedContent'], $config['disallowedContent']) = ckeditor5_get_acf_settings($format);

  // Create a token for access to dialogs.
  if (in_array('backdropLink.BackdropLink', $plugin_list)) {
    $link_token = filter_editor_dialog_token($format, 'link');
    $config['backdropLink']['dialogUrl'] = url('editor/dialog/link/' . $format->format, array('query' => array('token' => $link_token, 'calling_path' => $_GET['q'])));
    $config['backdropLink']['buttonLabel'] = t('Advanced');
  }
  if (in_array('backdropImage.BackdropImage', $plugin_list)) {
    $image_token = filter_editor_dialog_token($format, 'image');
    $config['backdropImage']['dialogUrl'] = url('editor/dialog/image/'. $format->format, array('query' => array('token' => $image_token, 'calling_path' => $_GET['q'])));
    $config['backdropImage']['uploadUrl'] = url('ckeditor5/upload/image/'. $format->format, array('query' => array('token' => $image_token, 'calling_path' => $_GET['q'])));
  }
  if (in_array('backdropImageCaption.BackdropImageCaption', $plugin_list)) {
    $config['backdropImageCaption']['captionFilterEnabled'] = !empty($format->filters['filter_image_caption']->status);
    $config['backdropImageCaption']['alignFilterEnabled'] = !empty($format->filters['filter_image_align']->status);
    $config['backdropImageCaption']['imageCaptionPlaceholderText'] = t('Enter caption text here.');
  }
  // Add the style list if configured.
  if (in_array('style.Style', $plugin_list)) {
    if (!empty($format->editor_settings['style_list'])) {
      $style_list = $format->editor_settings['style_list'];
      $config['style']['definitions'] = $style_list;
    }
  }

  // Add heading list if configured.
  if (in_array('heading.Heading', $plugin_list)) {
    $html_restrictions = filter_format_allowed_html($format);
    $heading_list = $format->editor_settings['heading_list'];
    $possible_headings = array(
      'h1' => array('model' => 'heading1', 'view' => 'h1', 'title' => t('Heading 1')),
      'h2' => array('model' => 'heading2', 'view' => 'h2', 'title' => t('Heading 2')),
      'h3' => array('model' => 'heading3', 'view' => 'h3', 'title' => t('Heading 3')),
      'h4' => array('model' => 'heading4', 'view' => 'h4', 'title' => t('Heading 4')),
      'h5' => array('model' => 'heading5', 'view' => 'h5', 'title' => t('Heading 5')),
      'h6' => array('model' => 'heading6', 'view' => 'h6', 'title' => t('Heading 6')),
    );
    foreach ($possible_headings as $tag => $heading_config) {
      // Remove if not enabled in the editor settings.
      if (!in_array($tag, $heading_list)) {
        unset($possible_headings[$tag]);
      }
      // Or remove if the HTML filter does not allow it.
      if (is_array($html_restrictions) && !isset($html_restrictions['allowed'][$tag])) {
        unset($possible_headings[$tag]);
      }
    }
    $config['heading']['options'] = array_values($possible_headings);
    // Add the always required normal paragraph formatting.
    array_unshift($config['heading']['options'], array(
      'model' => 'paragraph',
      'title' => t('Paragraph'),
    ));
  }

  backdrop_alter('ckeditor5_config', $config, $format);

  return $config;
}

/**
 * Builds the ACF part of the CKEditor JS settings.
 *
 * This ensures that CKEditor obeys the HTML restrictions defined by Backdrop's
 * filter system, by enabling CKEditor's Advanced Content Filter (ACF)
 * functionality: http://ckeditor5.com/blog/CKEditor-4.1-RC-Released.
 *
 * @param $format
 *   The text format object
 *
 * @return array
 *   An array with two values:
 *   - the first value is the "allowedContent" setting: a well-formatted array
 *     or TRUE. The latter indicates that anything is allowed.
 *   - the second value is the "disallowedContent" setting: a well-formatted
 *     array or FALSE. The latter indicates that nothing is disallowed.
 */
function ckeditor5_get_acf_settings($format) {
  $html_restrictions = filter_format_allowed_html($format);

  // When all HTML is allowed, also set allowedContent to true and
  // disallowedContent to false.
  if ($html_restrictions === TRUE) {
    return array(TRUE, FALSE);
  }

  /**
   * Converts Backdrop-stored attribute values to CKEditor attribute lists.
   */
  $get_attribute_values = function($attribute_values, $allowed_values) {
    $values = array_keys(array_filter($attribute_values, function($value) use ($allowed_values) {
      if ($allowed_values) {
        return $value !== FALSE;
      }
      else {
        return $value === FALSE;
      }
    }));
    if (count($values)) {
      return implode(',', $values);
    }
    else {
      return NULL;
    }
  };

  $allowed = array();
  $disallowed = array();
  if (isset($html_restrictions['forbidden'])) {
    foreach ($html_restrictions['forbidden'] as $tag) {
      $disallowed[$tag] = TRUE;
    }
  }
  foreach ($html_restrictions['allowed'] as $tag => $attributes) {
    // Tell CKEditor the tag is allowed, but no attributes.
    if ($attributes === FALSE) {
      $allowed[$tag] = array(
        'attributes' => FALSE,
        'styles' => FALSE,
        'classes' => FALSE,
      );
    }
    // Tell CKEditor the tag is allowed, as well as any attribute on it. The
    // "style" and "class" attributes are handled separately by CKEditor:
    // they are disallowed even if you specify it in the list of allowed
    // attributes, unless you state specific values for them that are
    // allowed. Or, in this case: any value for them is allowed.
    elseif ($attributes === TRUE) {
      $allowed[$tag] = array(
        'attributes' => TRUE,
        'styles' => TRUE,
        'classes' => TRUE,
      );
      // We've just marked that any value for the "style" and "class"
      // attributes is allowed. However, that may not be the case: the "*"
      // tag may still apply restrictions.
      // Since CKEditor's ACF follows the following principle:
      //     Once validated, an element or its property cannot be
      //     invalidated by another rule.
      // That means that the most permissive setting wins. Which means that
      // it will still be allowed by CKEditor to e.g. define any style, no
      // matter what the "*" tag's restrictions may be. If there's a setting
      // for either the "style" or "class" attribute, it cannot possibly be
      // more permissive than what was set above. Hence: inherit from the
      // "*" tag where possible.
      if (isset($html_restrictions['allowed']['*'])) {
        $wildcard = $html_restrictions['allowed']['*'];
        if (isset($wildcard['style'])) {
          if (!is_array($wildcard['style'])) {
            $allowed[$tag]['styles'] = $wildcard['style'];
          }
          else {
            $allowed_styles = $get_attribute_values($wildcard['style'], TRUE);
            if (isset($allowed_styles)) {
              $allowed[$tag]['styles'] = $allowed_styles;
            }
            else {
              unset($allowed[$tag]['styles']);
            }
          }
        }
        if (isset($wildcard['class'])) {
          if (!is_array($wildcard['class'])) {
            $allowed[$tag]['classes'] = $wildcard['class'];
          }
          else {
            $allowed_classes = $get_attribute_values($wildcard['class'], TRUE);
            if (isset($allowed_classes)) {
              $allowed[$tag]['classes'] = $allowed_classes;
            }
            else {
              unset($allowed[$tag]['classes']);
            }
          }
        }
      }
    }
    // Tell CKEditor the tag is allowed, along with some tags.
    elseif (is_array($attributes)) {
      // Configure allowed attributes, allowed "style" attribute values and
      // allowed "class" attribute values.
      // CKEditor only allows specific values for the "class" and "style"
      // attributes; so ignore restrictions on other attributes, which
      // Drupal filters may provide.
      // NOTE: A Drupal contrib module can subclass this class, override the
      // getConfig() method, and override the JavaScript at
      // Drupal.editors.ckeditor5 to somehow make validation of values for
      // attributes other than "class" and "style" work.
      $allowed_attributes = array_filter($attributes, function($value) {
        return $value !== FALSE;
      });
      if (count($allowed_attributes)) {
        $allowed[$tag]['attributes'] = implode(',', array_keys($allowed_attributes));
      }
      if (isset($allowed_attributes['style']) && is_array($allowed_attributes['style'])) {
        $allowed_styles = $get_attribute_values($allowed_attributes['style'], TRUE);
        if (isset($allowed_styles)) {
          $allowed[$tag]['styles'] = $allowed_styles;
        }
      }
      if (isset($allowed_attributes['class']) && is_array($allowed_attributes['class'])) {
        $allowed_classes = $get_attribute_values($allowed_attributes['class'], TRUE);
        if (isset($allowed_classes)) {
          $allowed[$tag]['classes'] = $allowed_classes;
        }
      }

      // Handle disallowed attributes analogously. However, to handle *dis-
      // allowed* attribute values, we must look at *allowed* attributes'
      // disallowed attribute values! After all, a disallowed attribute
      // implies that all of its possible attribute values are disallowed,
      // thus we must look at the disallowed attribute values on allowed
      // attributes.
      $disallowed_attributes = array_filter($attributes, function($value) {
        return $value === FALSE;
      });
      if (count($disallowed_attributes)) {
        // No need to blacklist the 'class' or 'style' attributes; CKEditor
        // handles them separately (if no specific class or style attribute
        // values are allowed, then those attributes are disallowed).
        if (isset($disallowed_attributes['class'])) {
          unset($disallowed_attributes['class']);
        }
        if (isset($disallowed_attributes['style'])) {
          unset($disallowed_attributes['style']);
        }
        $disallowed[$tag]['attributes'] = implode(',', array_keys($disallowed_attributes));
      }
      if (isset($allowed_attributes['style']) && is_array($allowed_attributes['style'])) {
        $disallowed_styles = $get_attribute_values($allowed_attributes['style'], FALSE);
        if (isset($disallowed_styles)) {
          $disallowed[$tag]['styles'] = $disallowed_styles;
        }
      }
      if (isset($allowed_attributes['class']) && is_array($allowed_attributes['class'])) {
        $disallowed_classes = $get_attribute_values($allowed_attributes['class'], FALSE);
        if (isset($disallowed_classes)) {
          $disallowed[$tag]['classes'] = $disallowed_classes;
        }
      }
    }
  }

  return array($allowed, $disallowed);
}

/**
 * Retrieves the default theme's CKEditor stylesheets defined in the .info file.
 *
 * Themes may specify iframe-specific CSS files for use with CKEditor by
 * including a "ckeditor5_stylesheets" key in the theme .info file.
 *
 * @code
 * ckeditor5_stylesheets[] = css/ckeditor5-iframe.css
 * @endcode
 *
 * @param string $theme
 *   The theme name from which the "ckeditor5_stylesheets" property should be
 *   read in the .info files. This theme and all its parent themes will be
 *   checked. Defaults to the current front-end theme.
 *
 * @return array
 *   An array of all CSS to be added by the theme within the CKEditor.
 */
function _ckeditor5_theme_css($theme = NULL) {
  $css = array();
  if (!isset($theme)) {
    $theme = config_get('system.core', 'theme_default');
  }
  if ($theme_path = backdrop_get_path('theme', $theme)) {
    $info = system_get_info('theme', $theme);
    if (isset($info['ckeditor5_stylesheets'])) {
      $css = $info['ckeditor5_stylesheets'];
      foreach ($css as $key => $path) {
        $css[$key] = $theme_path . '/' . $path;
      }
    }
    if (isset($info['base theme'])) {
      $css = array_merge($css, _ckeditor5_theme_css($info['base theme']));
    }
  }
  return $css;
}
