<?php
/**
 * @file
 * Install/uninstall and update functions for the standard installation profile.
 */

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function standard_install() {
  $system_config = config('system.core');

  // Set home page to "home".
  $system_config->set('site_frontpage', 'home');

  // Add default alias for page content types.
  config('path.settings')
    ->set('node_page_pattern', '[node:title]')
    ->set('node_post_pattern', 'posts/[node:title]')
    ->set('node_card_pattern', 'node/[node:nid]')
    ->save();

  cache_clear_all();

  // Create a default post to display on front page.
  $post = new Node(
    array(
      'title' => st('Your first post!'),
      'body' => array(
        LANGUAGE_NONE => array(
          array(
            'value' => '<p>' . st('This is your first post! You may edit or delete it.') . '</p>',
            'format' => 'filtered_html',
          ),
        ),
      ),
      'uid' => 1,
      'status' => 1,
      'promote' => 1,
      'type' => 'post',
    )
  );
  $post->save();

  // Create an "About" page node.
  $page = new Node(
    array(
      'title' => st('About'),
      'body' => array(
        LANGUAGE_NONE => array(
          array(
            'value' => '<p>' . st('This is a page with static content. You may edit or delete it.') . '</p>',
            'format' => 'filtered_html',
          ),
        ),
      ),
      'uid' => 1,
      'status' => 1,
      'promote' => 0,
      'type' => 'page',
    )
  );
  $page->save();

  // Creating three default Card nodes.
  // Special thanks to @indigoxela for providing the icons.
  $field_image_dir = 'public://field/image';
  file_prepare_directory($field_image_dir, FILE_CREATE_DIRECTORY);

  $cards = array(
    'card1-layout.png' => array(
      'title' => st('The Home page layout'),
      'body' => st('<p>Use the home page layout to specifically customize this page. These Cards only appear on this layout.</p><p><a href="https://docs.backdropcms.org/documentation/the-home-page">Learn more about the Home page</a></p>'),
    ),
    'card2-card.png' => array(
      'title' => st('What is a Card?'),
      'body' => st('<p>A Card can only be seen as part of another page. Place them individually as "Existing content" Blocks, or grouped as in a View.</p><p><a href="https://docs.backdropcms.org/documentation/creating-and-editing-content">Learn more about Cards</a></p>'),
    ),
    'card3-organize.png' => array(
      'title' => st('Organize your content'),
      'body' => st('<p>Backdrop CMS includes three pre-defined types of content: Pages, Posts, and Cards. Custom content types can also be added.</p><p><a href="https://docs.backdropcms.org/documentation/content-types">Learn more about content types</a></p>'),
    ),
  );

  foreach ($cards as $image_filename => $info) {
    $image_url = BACKDROP_ROOT . '/' . backdrop_get_path('profile', 'standard') . '/images/' . $image_filename;
    $moved_file = file_unmanaged_copy($image_url, $field_image_dir);

    $file = entity_create('file', array(
      'filename' => $image_filename,
      'uri' => $moved_file,
      'uid' => 1,
    ));
    $file->save();

    $card = new Node(
      array(
        'title' => $info['title'],
        'body' => array(
          LANGUAGE_NONE => array(
            array(
              'value' => $info['body'],
              'format' => 'filtered_html',
            ),
          ),
        ),
        'field_image' => array(
          LANGUAGE_NONE => array(
            array(
              'fid' => $file->fid,
              'filename' => $image_filename,
              'uri' => 'public://field/image/' . $image_filename,
              'filemime' => 'image/jpeg',
              'status' => 0,
            ),
          ),
        ),
        'uid' => 1,
        'status' => 1,
        'promote' => 1,
        'type' => 'card',
      )
    );
    $card->save();
  }

  // Modify the default promoted view to exclude cards.
  $promoted_view = views_get_view('promoted');
  $promoted_view->display['default']->display_options['filters']['type'] = array(
    'id' => 'type',
    'table' => 'node',
    'field' => 'type',
    'operator' => 'not in',
    'value' => array('card' => 'card'),
  );
  $promoted_view->save();

  // Enable default permissions for system roles.
  $anonymous_permissions = array(
    'access content',
    'access comments',
    'use text format filtered_html',
  );
  $authenticated_permissions = array(
    'access content',
    'access comments',
    'post comments',
    'skip comment approval',
    'upload editor images',
    'use text format filtered_html',
  );
  user_role_grant_permissions(BACKDROP_ANONYMOUS_ROLE, $anonymous_permissions);
  user_role_grant_permissions(BACKDROP_AUTHENTICATED_ROLE, $authenticated_permissions);

  // Set 'Administrator' as the administrator role.
  $system_config->set('user_admin_role', 'administrator');

  // Assign the "Administrator" role to user 1, and make sure that generation of
  // automatic path alias is enabled.
  $admin_user = user_load(1);
  $admin_user->roles[] = 'administrator';
  $admin_user->path['auto'] = TRUE;
  user_save($admin_user);

  // Create menu links.
  $item = array(
    'link_title' => st('Home'),
    'link_path' => '<front>',
    'menu_name' => 'main-menu',
    'weight' => -1,
  );
  menu_link_save($item);
  $item = array(
    'link_title' => 'About',
    'link_path' => 'node/' . $page->nid,
    'menu_name' => 'main-menu',
    'weight' => 1,
  );
  menu_link_save($item);
  $item = array(
    'link_title' => st('Login'),
    'link_path' => 'user/login',
    'menu_name' => 'user-menu',
    'weight' => -1,
  );
  menu_link_save($item);

  // Update the menu router information.
  menu_rebuild();

  // Enable default and admin themes.
  // @see system_install()
  $default_theme = 'basis';
  $admin_theme = 'seven';
  $system_config->set('theme_default', $default_theme);
  $system_config->set('admin_theme', $admin_theme);
  $system_config->set('node_admin_theme', '1');
  theme_enable(array($default_theme, $admin_theme));
  theme_disable(array('stark'));

  // Enable the page cache and aggregation.
  $system_config->set('preprocess_css', '1');
  $system_config->set('preprocess_js', '1');
  $system_config->set('cache', '1');

  # Save system config changes.
  $system_config->save();
  backdrop_flush_all_caches();
}
