name: Coding standards
on:
  pull_request:
    branches: [1.x]

jobs:
  phpcs:
    name: Run phpcs
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with CodeSniffer tool
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpcs, cs2pr
          coverage: none

      # The checkout action refuses to put it outside, so we have to do it in
      # two steps.
      - name: Checkout coding standard
        uses: actions/checkout@v4
        with:
          repository: backdrop-ops/phpcs
          ref: 1.1.0
          path: phpcs

      - name: Move standard outside current dir
        run: mv phpcs ..

      - name: Checkout code with full depth
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run phpcs on changed files
        run: |
          chmod 700 .github/misc/phpcs-changed-only.sh
          .github/misc/phpcs-changed-only.sh

      - name: On failure add report to job summary
        if: ${{ failure() }}
        run: |
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat /tmp/phpcs_summary >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  spellcheck:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout code
    - uses: streetsidesoftware/cspell-action@v5
      name: Run CSpell
      with:
        incremental_files_only: true
        config: '.cspell/cspell.json'
