name: Coding standards
on:
  pull_request:
    branches: [1.x]

jobs:
  phpcs:
    name: Run phpcs
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with CodeSniffer tool
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: phpcs

      # The checkout action refuses to put it outside, so we have to do it in
      # two steps.
      - name: Checkout coding standard
        uses: actions/checkout@v6
        with:
          repository: backdrop-ops/phpcs
          ref: 1.3.0
          path: phpcs

      - name: Move standard outside current dir
        run: mv phpcs ..

      - name: Checkout code with full depth
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run phpcs on changed code
        run: |
          chmod 700 .github/misc/phpcs-changeset-check.sh
          .github/misc/phpcs-changeset-check.sh origin/${{ github.base_ref }}

  spellcheck:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      name: Checkout code
    - uses: streetsidesoftware/cspell-action@v8
      name: Run CSpell
      with:
        incremental_files_only: true
        config: '.cspell/cspell.json'
