<?php
/**
 * @file
 * The Layout module creates pages and wraps existing pages in layouts.
 *
 * Backdrop's primary tool for positioning content is through layouts and
 * blocks. A "layout" is the template that defines regions in which pieces of
 * content may be placed. Each piece of content in this case is called a
 * "block". Blocks may be placed multiple times in a single layout, and each
 * block maintains separate settings. Each layout created saves to a
 * configuration file, including all the settings for the blocks contained
 * within it.
 *
 * Layout module provides two distinct ways of rendering pages. It is capable of
 * creating a stand-alone page that is created at any custom path specified by
 * the user, and it can also "wrap" the content of any path provided by a
 * module. In the case where a custom path is created, Layout module registers
 * the path in the menu system through hook_menu(). For wrapping module-provided
 * pages, Layout module declares itself as the system-wide "route handler", as
 * checked in menu_execute_active_handler(). Layout module then becomes
 * responsible for calling the module-provided content as a block, and positions
 * other blocks around the existing content.
 */

include_once('dashboard.inc');

/**
 * Implements hook_menu().
 *
 * Adds the total control dashboard
 */
function dashboard_menu() {
  $items = array();

  // Add a tab for the dashboard.
  $items['admin/dashboard'] = array(
    'title' => 'Dashboard',
    'page callback' => 'dashboard',
    'description' => 'Total Control admin dashboard',
    'access arguments' => array('access content'),
    'weight' => -100,
  );

  // Add a tab for the dashboard.
  $items['admin/dashboard/overview'] = array(
    'title' => 'Dashboard',
    'description' => 'Total Control admin dashboard',
    'access arguments' => array('access content'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -100,
  );

  return $items;
}

/**
 * Implements hook_block_info().
 */
function dashboard() {
  return t('Welcome');
}

/**
 * Implements hook_block_info().
 */
function dashboard_block_info() {
  $blocks['content'] = array(
    'info' => t('Dashboard welcome'),
    'description' => t('Intro to Total Control'),
    'class' => 'DashboardWelcomeBlock',
  );
  $blocks['create'] = array(
    'info' => t('Dashboard create content'),
    'description' => t('Provides links to create new content'),
    'class' => 'DashboardCreateBlock',
  );
  $blocks['menu'] = array(
    'info' => t('Dashboard admin - Menus'),
    'description' => t('Provides links to administer menus'),
    'class' => 'DashboardMenuBlock',
  );
  $blocks['node_types'] = array(
    'info' => t('Dashboard admin - Content types'),
    'description' => t('Provides links to administer content types'),
    'class' => 'DashboardContentTypesBlock',
  );
  $blocks['overview'] = array(
    'info' => t('Dashboard overview - Content & User accounts'),
    'description' => t('An overview of both content and users in one block'),
    'class' => 'DashboardOverviewBlock',
  );
  $blocks['overview_content'] = array(
    'info' => t('Dashboard overview - Content'),
    'description' => t('Displays a summary of content statistics'),
    'class' => 'DashboardOverviewContentBlock',
  );
  $blocks['overview_user'] = array(
    'info' => t('Dashboard overview - User accounts'),
    'description' => t('Displays a summary of user statistics'),
    'class' => 'DashboardOverviewUserBlock',
  );
  $blocks['taxonomy'] = array(
    'info' => t('Dashboard admin - Taxonomy'),
    'description' => t('Provides links to administer taxonomy'),
    'class' => 'DashboardTaxonomyBlock',
  );

  return $blocks;
}

/**
 * Implements hook_autoload_info().
 */
function dashboard_autoload_info() {
  return array(
    'DashboardBlock' => 'includes/dashboard_block.inc',
    'DashboardWelcomeBlock' => 'includes/welcome.inc',
    'DashboardCreateBlock' => 'includes/create.inc',
    'DashboardMenuBlock' => 'includes/menus.inc',
    'DashboardContentTypesBlock' => 'includes/node_types.inc',
    'DashboardOverviewBlock' => 'includes/overview.inc',
    'DashboardOverviewContentBlock' => 'includes/overview_content.inc',
    'DashboardOverviewUserBlock' => 'includes/overview_user.inc',
    'DashboardTaxonomyBlock' => 'includes/taxonomy.inc',
  );
}

/**
 * Implements hook_theme().
 *
 * Adds theme functions for the output of content panes.
 */
function dashboard_theme() {
  return array(
    'dashboard_create' => array(
      'variables' => array('create' => array()),
      'file' => 'dashboard.theme.inc',
    ),
    'dashboard_overview' => array(
      'variables' => array('content' => array(), 'users' => array()),
      'file' => 'dashboard.theme.inc',
    ),
    'dashboard_overview_content' => array(
      'variables' => array('overview' => array()),
      'file' => 'dashboard.theme.inc',
    ),
    'dashboard_overview_user' => array(
      'variables' => array('overview' => array()),
      'file' => 'dashboard.theme.inc',
    ),
    'dashboard_admin_table' => array(
      'variables' => array('header' => array(), 'rows' => array(), 'link' => FALSE),
      'file' => 'dashboard.theme.inc',
    ),
  );
}

